services:
  postgres-db:
    image: postgres:15
    container_name: topics_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

  topics-app:
    image: ethanrobv/topics:latest
    container_name: topics_app
    ports:
      - "80:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_R2DBC_URL: r2dbc:pool:postgresql://postgres-db:5432/${POSTGRES_DB}
      SPRING_R2DBC_USERNAME: ${POSTGRES_USER}
      SPRING_R2DBC_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_FLYWAY_URL: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      SPRING_FLYWAY_USER: ${POSTGRES_USER}
      SPRING_FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres-dev-data:
